name: dmhytool
description: "A rss tool on windows"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.3.0
  path_provider: ^2.1.4
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

